/**
 * Generate executor/skills/THIRD_PARTY_LICENSES.md from the per-skill
 * manifests + PROVENANCE.json records. Deterministic (sorted, no
 * timestamps) so the freshness gate is regenerate + compare.
 *
 *   npm run licenses          # write the roll-up
 *   npm run licenses:check    # exit 1 when the committed file is stale
 *
 * The audit output is the table itself: every third-party skill, its
 * license, its upstream repo at a pinned commit, and whether the content
 * is vendored (LICENSE file on disk) or reference-only (fetched live at
 * install time, never committed).
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { generateRegistry, SKILLS_DIR, type SkillManifest } from '../src/agent/skills.js'

interface Provenance {
  repo: string
  commit: string
  fetchedAt: string
  upstreamPath: string
  licenseFile: string | null
  note?: string
}

/** Deterministic markdown for the current registry. Exported so the
 *  freshness gate compares without shelling out. */
export function renderThirdPartyLicenses (skillsDir: string = SKILLS_DIR): string {
  const thirdParty = generateRegistry(skillsDir).skills
    .filter((s: SkillManifest) => s.provider !== 'ABC')

  const lines: string[] = [
    '# Third-party licenses',
    '',
    'Generated by `npm run licenses` from the skill manifests and PROVENANCE.json records.',
    'Do not edit by hand — the freshness gate regenerates and compares.',
    '',
    '| Skill | Provider | License | Upstream | Content |',
    '| --- | --- | --- | --- | --- |'
  ]

  for (const s of thirdParty) {
    const provPath = join(skillsDir, s.slug, 'PROVENANCE.json')
    const prov: Provenance | null = existsSync(provPath)
      ? JSON.parse(readFileSync(provPath, 'utf8')) as Provenance
      : null
    const upstream = prov ? `${prov.repo} @ \`${prov.commit.slice(0, 12)}\`` : s.sourceUrl
    const content = s.referenceOnly
      ? 'reference-only (fetched at install)'
      : `vendored verbatim${prov?.licenseFile ? `, \`${prov.licenseFile}\`` : ''}`
    lines.push(`| ${s.slug} | ${s.provider} | ${s.licenseSpdx} | ${upstream} | ${content} |`)
  }

  lines.push('')
  const vendored = thirdParty.filter(s => !s.referenceOnly)
  const reference = thirdParty.filter(s => s.referenceOnly)
  lines.push(
    `Vendored: ${vendored.length} skill(s) with their upstream LICENSE files on disk.`,
    `Reference-only: ${reference.length} catalog entr${reference.length === 1 ? 'y' : 'ies'} whose upstream repos carry no license;`,
    'their content is fetched live at the operator\'s explicit install command and is never committed.',
    ''
  )
  return lines.join('\n')
}

const isMain = process.argv[1] != null && import.meta.url === new URL(`file://${process.argv[1]}`).href
if (isMain) {
  const out = join(SKILLS_DIR, 'THIRD_PARTY_LICENSES.md')
  const rendered = renderThirdPartyLicenses()
  if (process.argv.includes('--check')) {
    const committed = existsSync(out) ? readFileSync(out, 'utf8') : ''
    if (committed !== rendered) {
      console.error('[licenses] THIRD_PARTY_LICENSES.md is stale — run npm run licenses')
      process.exit(1)
    }
    console.log('[licenses] THIRD_PARTY_LICENSES.md is fresh')
  } else {
    writeFileSync(out, rendered)
    console.log(`[licenses] THIRD_PARTY_LICENSES.md written (${renderThirdPartyLicenses().split('\n').length} lines)`)
  }
}
