// End-to-end test of the LGE v2 flow on Arc testnet, driven through the
// CONSOLE's own artifacts: bytecode constants, ABIs, and addresses are
// extracted from console/src/config/contracts (generated by sync-console.mjs
// from the linked deploy build), and each on-chain call mirrors the exact
// code path a user would trigger in the UI.
//
//   create campaign (mine salt locally, manager.deployToken)
//   -> deposit (calculateUsdcNeeded at current block + 5% slippage)
//   -> price rises with blocks
//   -> fill cap -> pool init + LP mint + treasury buy (vesting + escrow)
//   -> claimLiquidity records an LP share (no NFT transfer in v2)
//   -> third-party swap via E2ESwapExecutor -> hook fee -> participant/agent
//      claims -> protocol sweep correctly refuses below MIN_SWEEP
//   -> second campaign, short window expires, withdraw
//
// Usage: PRIVATE_KEY=0x... node e2e.mjs   (deployer key, funds a fresh user)
// Requires: viem@2.37.9. Run AFTER sync-console.mjs (needs deployments/<id>.json
// and the generated console consts).

import { readFileSync } from 'node:fs'
import {
  createPublicClient, createWalletClient, http, defineChain,
  keccak256, encodePacked, encodeAbiParameters, concat, getCreate2Address,
  formatEther
} from 'viem'
import { privateKeyToAccount, generatePrivateKey } from 'viem/accounts'

const ROOT = new URL('..', import.meta.url).pathname
const CONSOLE = process.env.ABC_CONSOLE_DIR || `${ROOT}../console`

// ---------- extract console artifacts ----------
function extractConst (file, name) {
  const src = readFileSync(`${CONSOLE}/${file}`, 'utf8')
  const re = new RegExp(name + '\\s*=\\s*["\'](0x[0-9a-fA-F]+)["\']')
  const m = src.match(re)
  if (!m) throw new Error(`const ${name} not found in ${file}`)
  return m[1]
}
function extractAbi (file) {
  // ABI files are TS object literals (unquoted keys) - evaluate as JS
  const src = readFileSync(`${CONSOLE}/${file}`, 'utf8')
  const start = src.indexOf('[')
  const end = src.lastIndexOf(']')
  return new Function(`return (${src.slice(start, end + 1)})`)()
}

const HOOK_BYTECODE = extractConst('src/config/contracts/bytecode/LGEHookBytecode.ts', 'LGE_HOOK_BYTECODE_ARC_TESTNET')
const TOKEN_BYTECODE = extractConst('src/config/contracts/bytecode/LGETokenBytecode.ts', 'LGE_TOKEN_BYTECODE_ARC_TESTNET')
const MANAGER_ABI = extractAbi('src/config/contracts/abis/LGEManagerAbi.ts')
const HOOK_ABI = extractAbi('src/config/contracts/abis/LGEHookAbi.ts')
const LIB_ABI = extractAbi('src/config/contracts/abis/LGECalculationsLibraryAbi.ts')
const TOKEN_ABI = extractAbi('src/config/contracts/abis/LGETokenAbi.ts')
const VESTING_ABI = extractAbi('src/config/contracts/abis/VestingVaultAbi.ts')
const ESCROW_ABI = extractAbi('src/config/contracts/abis/InferenceEscrowAbi.ts')
console.log('[artifacts] hook bytecode %d bytes, token bytecode %d bytes, ABIs loaded',
  (HOOK_BYTECODE.length - 2) / 2, (TOKEN_BYTECODE.length - 2) / 2)

// ---------- deployment addresses ----------
const deploy = JSON.parse(readFileSync(`${ROOT}deployments/5042002.json`, 'utf8'))
const MANAGER = deploy.lgeManager
const LIB = deploy.calculationsLibrary
const POOL_MANAGER = deploy.poolManager
const POSITION_MANAGER = deploy.positionManager
const PERMIT2 = deploy.permit2
const VESTING = deploy.vestingVault
const ESCROW = deploy.inferenceEscrow
const PROTOCOL = deploy.protocol

const arcTestnet = defineChain({
  id: 5042002,
  name: 'Arc Testnet',
  nativeCurrency: { name: 'USDC', symbol: 'USDC', decimals: 18 },
  rpcUrls: { default: { http: [process.env.ARC_RPC_URL || 'https://rpc.testnet.arc.io'] } }
})

const GAS = { maxFeePerGas: 20_000_000_000n, maxPriorityFeePerGas: 1_000_000_000n }
const publicClient = createPublicClient({ chain: arcTestnet, transport: http(arcTestnet.rpcUrls.default.http[0]) })

// Arc RPC intermittently answers heavy eth_call with -32003; mirror wagmi's
// react-query retry behaviour.
async function readWithRetry (params, attempts = 6) {
  for (let i = 1; ; i++) {
    try {
      return await publicClient.readContract(params)
    } catch (e) {
      const transient = String(e?.cause?.code ?? e?.code) === '-32003' || /Transaction creation failed/.test(e.message)
      if (!transient || i === attempts) throw e
      console.log('[rpc] transient -32003 on %s, retry %d/%d', params.functionName, i, attempts)
      await new Promise(r => setTimeout(r, 2000 * i))
    }
  }
}

const deployer = privateKeyToAccount(process.env.PRIVATE_KEY)
const user = privateKeyToAccount(generatePrivateKey())
const userWallet = createWalletClient({ account: user, chain: arcTestnet, transport: http(arcTestnet.rpcUrls.default.http[0]) })
const deployerWallet = createWalletClient({ account: deployer, chain: arcTestnet, transport: http(arcTestnet.rpcUrls.default.http[0]) })

// v2 launch params (per-launch on the hook). Prices are raw tokens-per-USDC
// ratios (both legs 18-dec): 20k-80k tokens/USDC -> a full raise is ~0.8 USDC.
const LAUNCH = {
  cap: 20_000n * 10n ** 18n,
  streamBlocks: 3600n,
  minTokenPrice: 20_000n,
  maxTokenPrice: 80_000n,
  exitThreshold: 0n, // exits disabled for the e2e (forge covers exit paths)
  feeBps: 100,
  vestingCliff: 0n,
  vestingDuration: BigInt(365 * 24 * 3600)
}

async function mineAndCreate ({ name, symbol, streamBlocks }) {
  const block = await publicClient.getBlock()
  const tokenSalt = keccak256(encodePacked(['address', 'uint256'], [user.address, block.timestamp]))
  const tokenCtor = encodeAbiParameters(
    [{ type: 'string' }, { type: 'string' }, { type: 'address' }, { type: 'string' }, { type: 'string' }, { type: 'address' }, { type: 'uint256' }],
    [name, symbol, user.address, '', '', MANAGER, LAUNCH.cap])
  const tokenAddress = getCreate2Address({
    from: MANAGER, salt: tokenSalt,
    bytecodeHash: keccak256(concat([TOKEN_BYTECODE, tokenCtor]))
  })
  const startBlock = block.number + 10n

  // HookParams struct (single tuple constructor arg in v2)
  const hookParams = {
    poolManager: POOL_MANAGER, positionManager: POSITION_MANAGER, permit2: PERMIT2,
    token: tokenAddress, agent: user.address, protocol: PROTOCOL,
    vestingVault: VESTING, inferenceEscrow: ESCROW,
    startBlock, streamBlocks,
    minTokenPrice: LAUNCH.minTokenPrice, maxTokenPrice: LAUNCH.maxTokenPrice,
    exitThreshold: LAUNCH.exitThreshold, feeBps: LAUNCH.feeBps,
    vestingCliff: LAUNCH.vestingCliff, vestingDuration: LAUNCH.vestingDuration
  }
  const hookCtor = encodeAbiParameters(
    [{ type: 'tuple', components: [
      { name: 'poolManager', type: 'address' }, { name: 'positionManager', type: 'address' },
      { name: 'permit2', type: 'address' }, { name: 'token', type: 'address' },
      { name: 'agent', type: 'address' }, { name: 'protocol', type: 'address' },
      { name: 'vestingVault', type: 'address' }, { name: 'inferenceEscrow', type: 'address' },
      { name: 'startBlock', type: 'uint256' }, { name: 'streamBlocks', type: 'uint256' },
      { name: 'minTokenPrice', type: 'uint256' }, { name: 'maxTokenPrice', type: 'uint256' },
      { name: 'exitThreshold', type: 'uint256' }, { name: 'feeBps', type: 'uint24' },
      { name: 'vestingCliff', type: 'uint64' }, { name: 'vestingDuration', type: 'uint64' }
    ] }],
    [hookParams])

  // Salt mining done LOCALLY (pure keccak, mirrors HookMiner.find exactly).
  // The manager re-validates the flags on-chain in deployToken.
  const flags = await readWithRetry({ address: MANAGER, abi: MANAGER_ABI, functionName: 'FLAGS' })
  const initCodeHash = keccak256(concat([HOOK_BYTECODE, hookCtor]))
  let hookAddress, hookSalt
  for (let i = 0; i < 20_000_000; i++) {
    const salt = ('0x' + i.toString(16).padStart(64, '0'))
    const addr = getCreate2Address({ from: MANAGER, salt, bytecodeHash: initCodeHash })
    if ((BigInt(addr) & 0x3fffn) === BigInt(flags)) {
      const code = await publicClient.getCode({ address: addr })
      if (!code || code === '0x') { hookAddress = addr; hookSalt = salt; break }
    }
    if (i > 0 && i % 2_000_000 === 0) console.log('[mine] %d iterations...', i)
  }
  if (!hookAddress) throw new Error('no salt found in 20M iterations')

  const hash = await userWallet.writeContract({
    address: MANAGER, abi: MANAGER_ABI, functionName: 'deployToken',
    args: [{
      tokenConfig: { tokenAdmin: user.address, name, symbol, image: '', metadata: '', cap: LAUNCH.cap, tokenSalt },
      hookConfig: {
        hookSalt, startBlock, streamBlocks,
        minTokenPrice: LAUNCH.minTokenPrice, maxTokenPrice: LAUNCH.maxTokenPrice,
        exitThreshold: LAUNCH.exitThreshold, feeBps: LAUNCH.feeBps,
        vestingCliff: LAUNCH.vestingCliff, vestingDuration: LAUNCH.vestingDuration
      }
    }],
    ...GAS
  })
  const receipt = await publicClient.waitForTransactionReceipt({ hash })
  if (receipt.status !== 'success') throw new Error('deployToken reverted')
  const token = await publicClient.getCode({ address: tokenAddress })
  const hook = await publicClient.getCode({ address: hookAddress })
  if (!token || token === '0x') throw new Error('token not at precomputed address')
  if (!hook || hook === '0x') throw new Error('hook not at mined address')
  console.log('[create] %s: token=%s hook=%s startBlock=%s (gas %s)', symbol, tokenAddress, hookAddress, startBlock, receipt.gasUsed)
  return { tokenAddress, hookAddress, startBlock, streamBlocks }
}

async function waitForStart (startBlock) {
  for (;;) {
    const b = await publicClient.getBlockNumber()
    if (b >= startBlock) return
    await sleep(1_000)
  }
}

async function deposit ({ hookAddress, startBlock, streamBlocks, amount, label }) {
  // mirrors the console deposit flow: quote at current block + 5% slippage
  await waitForStart(startBlock)
  const currentBlock = await publicClient.getBlockNumber()
  const needed = await readWithRetry({
    address: LIB, abi: LIB_ABI, functionName: 'calculateUsdcNeeded',
    args: [currentBlock, startBlock, streamBlocks, LAUNCH.minTokenPrice, LAUNCH.maxTokenPrice, amount]
  })
  const value = (needed * 105n) / 100n
  const hash = await userWallet.writeContract({
    address: hookAddress, abi: HOOK_ABI, functionName: 'deposit',
    args: [amount], value, ...GAS
  })
  const receipt = await publicClient.waitForTransactionReceipt({ hash })
  if (receipt.status !== 'success') throw new Error(`deposit reverted (${label})`)
  console.log('[deposit] %s: %s tokens for ~%s USDC (gas %s)', label, amount / 10n ** 18n, formatEther(needed), receipt.gasUsed)
}

async function priceAt (startBlock, streamBlocks) {
  const b = await publicClient.getBlockNumber()
  return readWithRetry({
    address: LIB, abi: LIB_ABI, functionName: 'calculateCurrentTokenPrice',
    args: [b, startBlock, streamBlocks, LAUNCH.minTokenPrice, LAUNCH.maxTokenPrice]
  })
}

const sleep = ms => new Promise(r => setTimeout(r, ms))

async function main () {
  console.log('[setup] user wallet (fresh):', user.address)
  const fundTx = await deployerWallet.sendTransaction({ to: user.address, value: 3n * 10n ** 18n, ...GAS })
  await publicClient.waitForTransactionReceipt({ hash: fundTx })
  console.log('[setup] funded user with 3 testnet USDC, tx', fundTx)

  // ---- campaign D first: short window ticks while we run campaign C ----
  const d = await mineAndCreate({ name: 'E2E Fail Path', symbol: 'E2EF', streamBlocks: 60n })
  await deposit({ ...d, amount: 100n * 10n ** 18n, label: 'D partial' })

  // ---- campaign C: full success path through the UI code paths ----
  const c = await mineAndCreate({ name: 'E2E Success Path', symbol: 'E2ES', streamBlocks: LAUNCH.streamBlocks })

  const p1 = await priceAt(c.startBlock, c.streamBlocks)
  await sleep(20_000)
  const p2 = await priceAt(c.startBlock, c.streamBlocks)
  if (p2 <= p1) throw new Error(`price did not rise: ${p1} -> ${p2}`)
  console.log('[price] rising curve confirmed: %s -> %s over ~20s', p1, p2)

  await deposit({ ...c, amount: 1_000n * 10n ** 18n, label: 'C small' })

  const cap = await readWithRetry({ address: c.tokenAddress, abi: TOKEN_ABI, functionName: 'cap' })
  const claimed = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'totalTokensClaimed' })
  await deposit({ ...c, amount: cap - claimed, label: 'C fill-cap (pool + LP + treasury buy)' })

  const success = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'isLgeSuccessful' })
  const posId = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'positionTokenId' })
  if (!success || posId === 0n) throw new Error(`LGE not successful: success=${success} posId=${posId}`)
  console.log('[success] pool initialized, hook-custodied LP position #%s', posId)

  // treasury half: 5% of supply vested to the agent, remainder in escrow
  const grant = await readWithRetry({ address: VESTING, abi: VESTING_ABI, functionName: 'grants', args: [c.tokenAddress, user.address] })
  const escrowed = await readWithRetry({ address: ESCROW, abi: ESCROW_ABI, functionName: 'creditOf', args: [user.address] })
  if (grant[0] === 0n) throw new Error('no vesting grant from treasury buy')
  console.log('[treasury] vested %s tokens to agent; inference escrow %s USDC', formatEther(grant[0]), formatEther(escrowed))

  // v2: claimLiquidity records a share; the LP NFT stays with the hook
  const claimTx = await userWallet.writeContract({
    address: c.hookAddress, abi: HOOK_ABI, functionName: 'claimLiquidity', ...GAS
  })
  const claimReceipt = await publicClient.waitForTransactionReceipt({ hash: claimTx })
  if (claimReceipt.status !== 'success') throw new Error('claimLiquidity reverted')
  const share = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'lpShares', args: [user.address] })
  if (share === 0n) throw new Error('no LP share recorded')
  console.log('[claim] user LP share recorded: %s', share)

  // ---- fee flow: third-party swap via the e2e executor ----
  const execArtifact = JSON.parse(readFileSync(`${ROOT}out/E2ESwapExecutor.sol/E2ESwapExecutor.json`, 'utf8'))
  const execHash = await deployerWallet.deployContract({
    abi: execArtifact.abi, bytecode: execArtifact.bytecode.object, args: [POOL_MANAGER], ...GAS
  })
  const execReceipt = await publicClient.waitForTransactionReceipt({ hash: execHash })
  const executor = execReceipt.contractAddress
  console.log('[swap] executor deployed at %s', executor)

  const poolKey = {
    currency0: '0x0000000000000000000000000000000000000000',
    currency1: c.tokenAddress,
    fee: 0, tickSpacing: 1, hooks: c.hookAddress
  }
  const swapIn = 2n * 10n ** 17n // 0.2 USDC
  const hookBalBefore = await publicClient.getBalance({ address: c.hookAddress })
  const swapTx = await userWallet.writeContract({
    address: executor, abi: execArtifact.abi, functionName: 'swapBuy',
    args: [poolKey, swapIn, 4295128740n, user.address], value: swapIn, ...GAS
  })
  const swapReceipt = await publicClient.waitForTransactionReceipt({ hash: swapTx })
  if (swapReceipt.status !== 'success') throw new Error('swapBuy reverted')
  const hookBalAfter = await publicClient.getBalance({ address: c.hookAddress })
  const expectedFee = (swapIn * 100n) / 10_000n
  if (hookBalAfter - hookBalBefore !== expectedFee) {
    throw new Error(`hook fee mismatch: got ${hookBalAfter - hookBalBefore}, want ${expectedFee}`)
  }
  console.log('[swap] buy filled, hook collected %s USDC fee', formatEther(expectedFee))

  // participant fees: claimable, then paid on claim
  const claimable = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'participantClaimable', args: [user.address] })
  if (claimable === 0n) throw new Error('no participant fees claimable')
  const userBalBefore = await publicClient.getBalance({ address: user.address })
  const pcTx = await userWallet.writeContract({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'claimParticipant', ...GAS })
  const pcReceipt = await publicClient.waitForTransactionReceipt({ hash: pcTx })
  if (pcReceipt.status !== 'success') throw new Error('claimParticipant reverted')
  const userBalAfter = await publicClient.getBalance({ address: user.address })
  const pcGas = pcReceipt.gasUsed * pcReceipt.effectiveGasPrice
  if (userBalAfter - userBalBefore + pcGas < claimable) throw new Error('participant claim underpaid')
  console.log('[fees] participant claimed %s USDC', formatEther(claimable))

  // agent fees (agent is the user here; claimAgent is a permissionless trigger)
  const agentAccrued = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'agentAccrued' })
  if (agentAccrued === 0n) throw new Error('no agent fees accrued')
  const acTx = await userWallet.writeContract({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'claimAgent', ...GAS })
  const acReceipt = await publicClient.waitForTransactionReceipt({ hash: acTx })
  if (acReceipt.status !== 'success') throw new Error('claimAgent reverted')
  console.log('[fees] agent claimed %s USDC', formatEther(agentAccrued))

  // protocol sweep must refuse: fees at this scale are below MIN_SWEEP (25 USDC)
  const protocolAccrued = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'protocolAccrued' })
  if (protocolAccrued === 0n) throw new Error('no protocol fees accrued')
  try {
    await publicClient.estimateContractGas({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'claimProtocol', account: user.address })
    throw new Error('claimProtocol should have reverted BelowMinSweep')
  } catch (e) {
    if (!/BelowMinSweep/.test(e.message)) throw e
    console.log('[fees] claimProtocol correctly reverts BelowMinSweep at %s USDC (< 25)', formatEther(protocolAccrued))
  }

  // lock state: booked << raised, so LP must be unlocked
  const locked = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'lpLocked' })
  const booked = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'participantFeesBooked' })
  const raised = await readWithRetry({ address: c.hookAddress, abi: HOOK_ABI, functionName: 'totalUsdcRaised' })
  if (locked) throw new Error('lpLocked true with booked < raised')
  console.log('[lock] lpLocked=false (booked %s / raised %s USDC)', formatEther(booked), formatEther(raised))

  // ---- campaign D: wait out the short window, then withdraw ----
  const streamEnd = d.startBlock + d.streamBlocks
  console.log('[withdraw] waiting for campaign D window (block > %s)...', streamEnd)
  for (;;) {
    const b = await publicClient.getBlockNumber()
    if (b > streamEnd) break
    process.stdout.write(`  block ${b}\r`)
    await sleep(5_000)
  }
  // a touch-in transaction finalizes the failed LGE (anyone can poke deposit(0)...
  // deposit of 0 reverts; withdraw itself checks the window, so just withdraw)
  const balBefore = await publicClient.getBalance({ address: user.address })
  const wTx = await userWallet.writeContract({
    address: d.hookAddress, abi: HOOK_ABI, functionName: 'withdraw', ...GAS
  })
  const wReceipt = await publicClient.waitForTransactionReceipt({ hash: wTx })
  if (wReceipt.status !== 'success') throw new Error('withdraw reverted')
  const balAfter = await publicClient.getBalance({ address: user.address })
  const gasCost = wReceipt.gasUsed * wReceipt.effectiveGasPrice
  if (balAfter <= balBefore - gasCost) throw new Error('no refund received')
  console.log('[withdraw] refund received: %s USDC (net of gas)', formatEther(balAfter - balBefore + gasCost))

  console.log('\nE2E PASS: create -> deposit -> rising price -> cap fill -> pool+LP -> treasury buy (vesting+escrow) -> LP share -> swap fees -> participant/agent claims -> protocol sweep floor -> lock state -> failed-LGE withdraw')
}

main().catch(e => { console.error('\nE2E FAIL:', e.message); process.exit(1) })
