// Syncs the console's contract artifacts from the DEPLOY BUILD:
//   - reads broadcast/Deploy.s.sol/<chain>/run-latest.json for addresses
//   - reads out/ artifacts (must be the FOUNDRY_LIBRARIES-linked build —
//     never run `forge test` between the deploy build and this script)
//   - writes contracts/deployments/<chain>.json
//   - writes console/src/config/contracts/{bytecode,abis,addresses}.ts
//
// Usage: node script/sync-console.mjs [chainId]   (default 5042002)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const ROOT = new URL('..', import.meta.url).pathname
const CONSOLE = process.env.ABC_CONSOLE_DIR || `${ROOT}../console`
const CHAIN_ID = process.argv[2] || '5042002'
const CHAIN_KEY = CHAIN_ID === '5042002' ? 'ARC_TESTNET' : `CHAIN_${CHAIN_ID}`

const broadcast = JSON.parse(
  readFileSync(`${ROOT}broadcast/Deploy.s.sol/${CHAIN_ID}/run-latest.json`, 'utf8')
)
const deployed = {}
for (const tx of broadcast.transactions) {
  if (tx.transactionType === 'CREATE' && tx.contractName) {
    deployed[tx.contractName] = tx.contractAddress
  }
}
for (const name of ['HookMinerWrapper', 'VestingVault', 'InferenceEscrow', 'HookCreationCode', 'LGEManager']) {
  if (!deployed[name]) throw new Error(`${name} not found in broadcast run`)
}

// Infra addresses come from the script's env (fixed Uniswap deployment on Arc).
const env = Object.fromEntries(readFileSync(`${ROOT}.env`, 'utf8').split('\n')
  .filter(l => l.includes('=') && !l.startsWith('#'))
  .map(l => { const i = l.indexOf('='); return [l.slice(0, i), l.slice(i + 1)] }))

const addresses = {
  chainId: Number(CHAIN_ID),
  poolManager: env.POOL_MANAGER,
  positionManager: env.POSITION_MANAGER,
  permit2: env.PERMIT2,
  protocol: env.PROTOCOL,
  hookMiner: deployed.HookMinerWrapper,
  vestingVault: deployed.VestingVault,
  inferenceEscrow: deployed.InferenceEscrow,
  hookCreationCode: deployed.HookCreationCode,
  lgeManager: deployed.LGEManager,
  calculationsLibrary: env.LIBRARY_ADDRESS || process.env.LIBRARY_ADDRESS || '',
  // Consoles/indexers scan TokenCreated from here, not from genesis.
  // LGEManager is the last tx of Deploy.s.sol; receipt blockNumbers are hex.
  managerDeployBlock: (() => {
    const r = broadcast.receipts?.[broadcast.receipts.length - 1]?.blockNumber
    return r ? Number(BigInt(r)) : 0
  })()
}
mkdirSync(`${ROOT}deployments`, { recursive: true })
writeFileSync(`${ROOT}deployments/${CHAIN_ID}.json`, JSON.stringify(addresses, null, 2) + '\n')

function artifact (name, file = name) {
  const a = JSON.parse(readFileSync(`${ROOT}out/${file}.sol/${name}.json`, 'utf8'))
  return a
}
function writeTs (rel, contents) {
  const path = `${CONSOLE}/src/config/contracts/${rel}`
  mkdirSync(path.slice(0, path.lastIndexOf('/')), { recursive: true })
  writeFileSync(path, contents)
  console.log('[sync] wrote', path)
}

// Bytecode consts (creation bytecode, library-linked for the hook).
for (const [name, file] of [['LGEHook', 'LGEHook'], ['LGEToken', 'LGEToken']]) {
  const a = artifact(name, file)
  const bc = a.bytecode?.object
  if (!bc || bc.length < 100 || bc.includes('$')) {
    throw new Error(`${name} bytecode missing or UNLINKED — rebuild with FOUNDRY_LIBRARIES set`)
  }
  const constName = name === 'LGEHook' ? 'LGE_HOOK_BYTECODE' : 'LGE_TOKEN_BYTECODE'
  writeTs(`bytecode/${name}Bytecode.ts`,
    `// GENERATED by contracts/script/sync-console.mjs from the linked deploy build. Do not edit.\n` +
    `export const ${constName}_${CHAIN_KEY} = '${bc}' as const\n`)
}

// ABIs
for (const [name, file] of [
  ['LGEManager', 'LGEManager'],
  ['LGEHook', 'LGEHook'],
  ['LGEToken', 'LGEToken'],
  ['LGECalculationsLibrary', 'LGECalculationsLibrary'],
  ['VestingVault', 'VestingVault'],
  ['InferenceEscrow', 'InferenceEscrow']
]) {
  const a = artifact(name, file)
  writeTs(`abis/${name}Abi.ts`,
    `// GENERATED by contracts/script/sync-console.mjs. Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(a.abi, null, 2)} as const\n`)
}

// Addresses
writeTs('addresses.ts',
  `// GENERATED by contracts/script/sync-console.mjs from broadcast/Deploy.s.sol/${CHAIN_ID}/run-latest.json. Do not edit.\n` +
  Object.entries(addresses).map(([k, v]) =>
    `export const ${k.replace(/([A-Z])/g, '_$1').toUpperCase()}_${CHAIN_KEY} = ${typeof v === 'number' ? v : `'${v}'`} as const`
  ).join('\n') + '\n')

console.log('[sync] deployments/%s.json + console consts up to date', CHAIN_ID)
