export const DEV_MODE = import.meta.env.DEV;

export const LGE_API_URL = import.meta.env.VITE_LGE_API_URL;

// ==== ETH SEPOLIA ====
export const LGE_MANAGER_ADDRESS_ETH_SEPOLIA = import.meta.env
  .VITE_LGE_MANAGER_ADDRESS_ETH_SEPOLIA;
export const LGE_CALCULATIONS_LIBRARY_ETH_SEPOLIA = import.meta.env
  .VITE_LGE_CALCULATIONS_LIBRARY_ETH_SEPOLIA;
export const POOL_MANAGER_ETH_SEPOLIA = import.meta.env
  .VITE_POOL_MANAGER_ETH_SEPOLIA;
export const POSITION_MANAGER_ETH_SEPOLIA = import.meta.env
  .VITE_POSITION_MANAGER_ETH_SEPOLIA;
export const PERMIT2_ETH_SEPOLIA = import.meta.env.VITE_PERMIT2_ETH_SEPOLIA;
export const HOOK_MINER_ETH_SEPOLIA = import.meta.env
  .VITE_HOOK_MINER_ETH_SEPOLIA;

// ==== UNICHAIN SEPOLIA ====
export const LGE_MANAGER_ADDRESS_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_LGE_MANAGER_ADDRESS_UNICHAIN_SEPOLIA;
export const LGE_CALCULATIONS_LIBRARY_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_LGE_CALCULATIONS_LIBRARY_UNICHAIN_SEPOLIA;
export const POOL_MANAGER_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_POOL_MANAGER_UNICHAIN_SEPOLIA;
export const POSITION_MANAGER_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_POSITION_MANAGER_UNICHAIN_SEPOLIA;
export const PERMIT2_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_PERMIT2_UNICHAIN_SEPOLIA;
export const HOOK_MINER_UNICHAIN_SEPOLIA = import.meta.env
  .VITE_HOOK_MINER_UNICHAIN_SEPOLIA;

// ==== ARC TESTNET ====
export const LGE_MANAGER_ADDRESS_ARC_TESTNET = import.meta.env
  .VITE_LGE_MANAGER_ADDRESS_ARC_TESTNET;
export const LGE_CALCULATIONS_LIBRARY_ARC_TESTNET = import.meta.env
  .VITE_LGE_CALCULATIONS_LIBRARY_ARC_TESTNET;
export const POOL_MANAGER_ARC_TESTNET = import.meta.env
  .VITE_POOL_MANAGER_ARC_TESTNET;
export const POSITION_MANAGER_ARC_TESTNET = import.meta.env
  .VITE_POSITION_MANAGER_ARC_TESTNET;
export const PERMIT2_ARC_TESTNET = import.meta.env.VITE_PERMIT2_ARC_TESTNET;
export const HOOK_MINER_ARC_TESTNET = import.meta.env
  .VITE_HOOK_MINER_ARC_TESTNET;
