// GENERATED by contracts/script/sync-console.mjs. Do not edit.
export const LGEManagerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "poolManager_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "positionManager_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "permit2_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "vestingVault_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "inferenceEscrow_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "protocol_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hookCreationCode_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "FLAGS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint160",
        "internalType": "uint160"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_hookCreationCode",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_inferenceEscrow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_permit2",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_poolManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_positionManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_protocol",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "_vestingVault",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployToken",
    "inputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct LGEManager.DeploymentConfig",
        "components": [
          {
            "name": "tokenConfig",
            "type": "tuple",
            "internalType": "struct LGEManager.TokenConfig",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "cap",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "tokenSalt",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "hookConfig",
            "type": "tuple",
            "internalType": "struct LGEManager.HookConfig",
            "components": [
              {
                "name": "hookSalt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "startBlock",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "streamBlocks",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "minTokenPrice",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "maxTokenPrice",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "exitThreshold",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "feeBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "vestingCliff",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "vestingDuration",
                "type": "uint64",
                "internalType": "uint64"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "tokenAddress",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hookAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "TokenCreated",
    "inputs": [
      {
        "name": "msgSender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenAddress",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "hookAddress",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "HookDeployFailed",
    "inputs": []
  }
] as const
